# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-11 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plt_icon',
            field=models.URLField(default='', verbose_name='第三方平台的头像 URL'),
        ),
    ]
